from __future__ import annotations

import sqlite3
from pathlib import Path

import yaml

from src.main import main


def _write_review_yaml(path: Path) -> None:
    payload = {
        "research_question": "How does automated tutoring impact learning outcomes?",
        "review_type": "systematic",
        "pico": {
            "population": "students",
            "intervention": "ai tutor",
            "comparison": "traditional instruction",
            "outcome": "learning outcomes",
        },
        "keywords": ["ai tutor", "education"],
        "domain": "education",
        "scope": "health sciences",
        "inclusion_criteria": ["peer reviewed studies"],
        "exclusion_criteria": ["opinion pieces"],
        "date_range_start": 2015,
        "date_range_end": 2026,
        "target_databases": ["unsupported_db"],
        "target_sections": ["abstract", "methods", "results"],
    }
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def _write_settings_yaml(path: Path) -> None:
    payload = {
        "agents": {
            "screening_reviewer_a": {"model": "google-gla:gemini-2.5-flash-lite", "temperature": 0.1},
            "screening_reviewer_b": {"model": "google-gla:gemini-2.5-flash-lite", "temperature": 0.3},
            "screening_adjudicator": {"model": "google-gla:gemini-2.5-pro", "temperature": 0.2},
            "quality_assessment": {"model": "google-gla:gemini-2.5-pro", "temperature": 0.1},
            "search": {"model": "google-gla:gemini-2.5-flash", "temperature": 0.1},
            "extraction": {"model": "google-gla:gemini-2.5-pro", "temperature": 0.1},
            "writing": {"model": "google-gla:gemini-2.5-pro", "temperature": 0.2},
        }
    }
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def test_run_executes_single_path_orchestrator(tmp_path) -> None:
    review_path = tmp_path / "review.yaml"
    settings_path = tmp_path / "settings.yaml"
    log_root = tmp_path / "logs"
    output_root = tmp_path / "outputs"
    _write_review_yaml(review_path)
    _write_settings_yaml(settings_path)

    code = main(
        [
            "run",
            "--config",
            str(review_path),
            "--settings",
            str(settings_path),
            "--log-root",
            str(log_root),
            "--output-root",
            str(output_root),
        ]
    )
    assert code == 0

    run_summaries = list(log_root.rglob("run_summary.json"))
    assert run_summaries, "run_summary.json should be generated by run command"
    run_dir = run_summaries[0].parent
    runtime_db = run_dir / "runtime.db"
    assert runtime_db.exists()
    app_log = run_dir / "app.jsonl"
    assert app_log.exists(), "app.jsonl should be generated for structured logging"
    conn = sqlite3.connect(runtime_db)
    try:
        cursor = conn.execute("SELECT phase FROM checkpoints")
        phases = {str(row[0]) for row in cursor.fetchall()}
    finally:
        conn.close()
    assert {"phase_2_search", "phase_3_screening", "phase_4_extraction_quality", "phase_5_synthesis", "phase_6_writing"}.issubset(phases)
