graph TD
    citations_bibtex_formatter["bibtex_formatter"]
    citations_citation_manager["citation_manager"]
    citations_ieee_formatter["ieee_formatter"]
    config_config_loader["config_loader"]
    config_debug_config["debug_config"]
    deduplication["deduplication"]
    enrichment_paper_enricher["paper_enricher"]
    export_extraction_form_generator["extraction_form_generator"]
    export_latex_exporter["latex_exporter"]
    export_word_exporter["word_exporter"]
    extraction_data_extractor_agent["data_extractor_agent"]
    observability_cost_tracker["cost_tracker"]
    observability_metrics["metrics"]
    observability_tracing["tracing"]
    orchestration_database_connector_factory["database_connector_factory"]
    orchestration_handoff_protocol["handoff_protocol"]
    orchestration_topic_propagator["topic_propagator"]
    orchestration_workflow_graph["workflow_graph"]
    orchestration_workflow_initializer["workflow_initializer"]
    orchestration_workflow_manager["workflow_manager"]
    prisma_checklist_generator["checklist_generator"]
    prisma_prisma_generator["prisma_generator"]
    quality_grade_assessor["grade_assessor"]
    quality_quality_assessment_schemas["quality_assessment_schemas"]
    quality_risk_of_bias_assessor["risk_of_bias_assessor"]
    quality_template_generator["template_generator"]
    schemas_extraction_schemas["extraction_schemas"]
    schemas_screening_schemas["screening_schemas"]
    screening_base_agent["base_agent"]
    screening_fulltext_agent["fulltext_agent"]
    screening_title_abstract_agent["title_abstract_agent"]
    search_cache["cache"]
    search_connectors_base["base"]
    search_database_connectors["database_connectors"]
    search_exceptions["exceptions"]
    search_integrity_checker["integrity_checker"]
    search_multi_database_searcher["multi_database_searcher"]
    search_proxy_manager["proxy_manager"]
    search_rate_limiter["rate_limiter"]
    search_search_logger["search_logger"]
    search_search_strategy["search_strategy"]
    state_checkpoint_manager["checkpoint_manager"]
    state_state_store["state_store"]
    testing_stage_loader["stage_loader"]
    testing_stage_validators["stage_validators"]
    tools_database_search_tool["database_search_tool"]
    tools_exa_tool["exa_tool"]
    tools_query_builder_tool["query_builder_tool"]
    tools_tavily_tool["tavily_tool"]
    tools_tool_registry["tool_registry"]
    utils_circuit_breaker["circuit_breaker"]
    utils_log_context["log_context"]
    utils_logging_config["logging_config"]
    utils_pdf_retriever["pdf_retriever"]
    utils_retry_strategies["retry_strategies"]
    utils_screening_validator["screening_validator"]
    utils_state_serialization["state_serialization"]
    utils_text_cleaner["text_cleaner"]
    validation_prisma_validator["prisma_validator"]
    visualization_charts["charts"]
    writing_abstract_agent["abstract_agent"]
    writing_discussion_agent["discussion_agent"]
    writing_introduction_agent["introduction_agent"]
    writing_methods_agent["methods_agent"]
    writing_results_agent["results_agent"]