"""
Mermaid Diagram Generation Tool

Generates Mermaid diagrams dynamically based on diagram type and data.
Supports all Mermaid diagram types: flowchart, pie, mindmap, gantt, sankey, treemap, etc.
"""

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

try:
    import mermaid as md

    MERMAID_AVAILABLE = True
except ImportError:
    MERMAID_AVAILABLE = False
    logger.warning("mermaid-py not installed. Diagram generation will be disabled.")


def generate_mermaid_diagram(
    diagram_type: str,
    mermaid_code: str,
    output_dir: str,
    diagram_title: Optional[str] = None,
) -> str:
    """
    Generate Mermaid diagram from Mermaid code syntax.

    Args:
        diagram_type: Type of diagram (for filename) - pie, mindmap, flowchart, gantt, sankey, treemap, quadrant, xy, sequence, timeline
        mermaid_code: Complete Mermaid syntax code (generated by LLM)
        output_dir: Directory to save diagram
        diagram_title: Optional title for filename

    Returns:
        Path to generated SVG file

    Raises:
        ImportError: If mermaid-py is not installed
        ValueError: If diagram_type is invalid
    """
    if not MERMAID_AVAILABLE:
        raise ImportError("mermaid-py is not installed. Install it with: pip install mermaid-py")

    # Validate diagram type
    valid_types = [
        "pie",
        "mindmap",
        "flowchart",
        "gantt",
        "sankey",
        "treemap",
        "quadrant",
        "xy",
        "sequence",
        "timeline",
        "state",
        "class",
        "er",
        "journey",
        "block",
        "architecture",
    ]
    if diagram_type not in valid_types:
        raise ValueError(f"Invalid diagram_type: {diagram_type}. Must be one of {valid_types}")

    # Create output directory if it doesn't exist
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Generate filename
    safe_title = diagram_title.replace(" ", "_").lower() if diagram_title else "diagram"
    safe_title = "".join(c for c in safe_title if c.isalnum() or c in ("_", "-"))
    filename = f"{diagram_type}_{safe_title}.svg"
    filepath = output_path / filename

    try:
        # Create Mermaid diagram object from code
        diagram = md.Mermaid(mermaid_code)

        # mermaid-py uses mermaid.ink service by default
        # The Mermaid object when converted to string returns the diagram
        # For SVG output, we need to get the SVG content
        # mermaid-py may return HTML with embedded SVG or direct SVG
        diagram_str = str(diagram)

        # Save diagram content to file
        # If it's HTML, we'll save as HTML (browsers can render it)
        # If it's SVG, we'll save as SVG
        if diagram_str.strip().startswith("<svg") or diagram_str.strip().startswith("<?xml"):
            # Direct SVG content
            filepath.write_text(diagram_str, encoding="utf-8")
        elif "<svg" in diagram_str:
            # HTML with embedded SVG - extract SVG or save as HTML
            # For simplicity, save as HTML if it contains SVG
            html_path = filepath.with_suffix(".html")
            html_path.write_text(diagram_str, encoding="utf-8")
            logger.info(f"Generated Mermaid diagram as HTML (contains SVG): {html_path}")
            return str(html_path)
        else:
            # Unknown format - save as-is
            filepath.write_text(diagram_str, encoding="utf-8")

        logger.info(f"Generated Mermaid diagram: {filepath}")
        return str(filepath)

    except Exception as e:
        logger.error(f"Error generating Mermaid diagram: {e}", exc_info=True)
        raise RuntimeError(f"Failed to generate Mermaid diagram: {e}")


def create_mermaid_diagram_tool(output_dir: str):
    """
    Create a tool definition for Mermaid diagram generation.

    Args:
        output_dir: Default output directory for diagrams

    Returns:
        Tool object
    """
    from .tool_registry import Tool, ToolParameter

    def execute_fn(
        diagram_type: str,
        mermaid_code: str,
        output_dir_override: Optional[str] = None,
        diagram_title: Optional[str] = None,
    ) -> str:
        """Execute function for tool."""
        dir_to_use = output_dir_override or output_dir
        return generate_mermaid_diagram(
            diagram_type=diagram_type,
            mermaid_code=mermaid_code,
            output_dir=dir_to_use,
            diagram_title=diagram_title,
        )

    tool = Tool(
        name="generate_mermaid_diagram",
        description="""Generate a Mermaid diagram dynamically. Choose the best diagram type based on your data:
    - 'pie': For percentages/proportions (e.g., bias prevalence 65%)
    - 'mindmap': For themes/concepts radiating from central topic
    - 'flowchart': For processes, workflows, decision trees
    - 'gantt': For timelines, publication trends
    - 'sankey': For flows, transformations (e.g., papers through screening stages)
    - 'treemap': For hierarchical data, nested categories
    - 'quadrant': For two-dimensional comparisons
    - 'xy': For scatter plots, correlations
    - 'sequence': For interactions over time
    - 'timeline': For chronological events
    Returns path to SVG file.""",
        parameters=[
            ToolParameter(
                name="diagram_type",
                type="string",
                description="Type of diagram: pie, mindmap, flowchart, gantt, sankey, treemap, quadrant, xy, sequence, timeline",
                required=True,
                enum=[
                    "pie",
                    "mindmap",
                    "flowchart",
                    "gantt",
                    "sankey",
                    "treemap",
                    "quadrant",
                    "xy",
                    "sequence",
                    "timeline",
                ],
            ),
            ToolParameter(
                name="mermaid_code",
                type="string",
                description="Complete Mermaid syntax code for the diagram. Generate this based on the diagram type and your data. Examples provided in prompt.",
                required=True,
            ),
            ToolParameter(
                name="output_dir",
                type="string",
                description="Directory to save diagram SVG file",
                required=False,
            ),
            ToolParameter(
                name="diagram_title",
                type="string",
                description="Title for the diagram (used in filename)",
                required=False,
            ),
        ],
        execute_fn=execute_fn,
    )

    return tool
